version: '3'
services:
  main-container:
    image: "ubuntu:bionic"
    restart: on-failure

    build:
      context: .
      dockerfile: "Dockerfile"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/healthcheck"]
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - 9090:9090